wallpaper { 
  monitor = DP-1
  path = /home/steffen/Pictures/backgrounds/mountains.jpg
  fit_mode = cover
}

wallpaper { 
  monitor = DP-2
  path = /home/steffen/Pictures/backgrounds/mountains.jpg
  fit_mode = cover
}

wallpaper { 
  monitor = DP-3
  path = /home/steffen/Pictures/backgrounds/mountains.jpg
  fit_mode = cover
}

